# ---
# - hosts: all
#   become: true
#   tasks:

#     - name: check space
#       ansible.netcommon.cli_command:
#         command: df -h
---
- hosts: all
  gather_facts: no
  tasks:
    - shell: df -h
      register: ps

    - debug: var=ps.stdout_lines